server.port=${PORT:8080}
spring.application.name=mend
TMDB_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0NjYzNTBkNGY2NjkxYTUxMmNiMjVlOGJiN2U5OTczOSIsIm5iZiI6MTc4Njc0NTkyOS45ODMsInN1YiI6IjZhN2Y5NDQ5YjU1YTdhN2M4MTZjODhiNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.gZgiYaB6Xz7AXS07Cji8rd0tNdsMv1PaRLshx3MEWWY